name: Release

on:
  push:
    tags:
      - 'v*.*.*' # This will run on tags in the format vMAJOR.MINOR.PATCH

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Prepare Release Version
        id: prep_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/tags/v}

      - name: Zip extension
        run: zip -r chatflow-chrome-${{ steps.prep_version.outputs.version }}.zip chatflow-chrome/

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: chatflow-chrome-${{ steps.prep_version.outputs.version }}.zip
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.prep_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
